export const siteConfig = {
  name: "Mahmudul Hasan",
  firstName: "MAHMUDUL",
  lastName: ".H",
  tagline: "GoHighLevel CRM & Automation Specialist",
  description:
    "GoHighLevel CRM & Automation Specialist and performance marketer helping service businesses turn more leads into booked clients. 4+ years running Meta Ads, Google Ads, and LinkedIn campaigns plus 30+ GoHighLevel systems for 200+ clients across the US, UK, and Australia.",
  url: "https://mahmudulhasan.site",
  email: "hello@mahmudulhasan.site",
  phone: "+880 1735993166",
  whatsapp: "https://wa.me/+8801735993166",
  location: "Bogra, Bangladesh",
  bookingUrl:
    "https://link.mahmudulhasan.site/widget/booking/kN5UNPMnHRyaVheY5y5F",
  analyticsId: "G-L2RCTXMK5C",
  googleSiteVerification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || "",
  keywords: [
    "Mahmudul Hasan",
    "GoHighLevel Specialist",
    "GoHighLevel CRM Setup",
    "Performance Marketing Specialist",
    "Meta Ads Expert",
    "Google Ads Consultant",
    "Marketing Automation Specialist",
    "Full-Funnel Marketing",
    "B2B Lead Generation",
    "CRM Automation Bangladesh",
    "Media Buyer",
    "Digital Marketing Consultant",
    "Zapier Make Automation",
  ],
  avatar:
    "https://res.cloudinary.com/dhrw2imoh/image/upload/v1739885761/Mahmud_Linkedin_3000_x_3000_px_bthces.png",
  socials: [
    { label: "Facebook", href: "https://www.facebook.com/mahmudulbisd/" },
    { label: "LinkedIn", href: "https://linkedin.com/in/mahmudulbisd" },
    { label: "GitHub", href: "https://github.com/mahmudulbisd" },
    { label: "YouTube", href: "https://youtube.com/mahmudulbisd" },
    { label: "WhatsApp", href: "https://wa.me/+8801735993166" },
  ],
  stats: [
    { value: "200+", label: "International Clients" },
    { value: "30+", label: "GHL Systems Deployed" },
    { value: "7+", label: "Years Combined Experience" },
    { value: "4+", label: "Years in Paid Media" },
  ],
  brands: [
    "Meta Ads",
    "Google Ads",
    "LinkedIn Ads",
    "GoHighLevel",
    "Shopify",
    "WordPress",
  ],
  nav: [
    { name: "Home", href: "/" },
    { name: "Services", href: "/#services" },
    { name: "About", href: "/#about" },
    { name: "Portfolio", href: "/#portfolio" },
    { name: "Blog", href: "/blog" },
    { name: "Contact", href: "/#contact" },
  ],
};
